export const PERMISSIONS = [
  "organization.read",
  "organization.update",
  "department.create",
  "department.read",
  "department.update",
  "project.create",
  "project.read",
  "project.update",
  "project.archive",
  "project.manage_team",
  "user.create",
  "user.read",
  "user.update",
  "user.disable",
  "role.read",
  "role.assign",
  "document.upload",
  "document.read",
  "document.update",
  "document.approve",
  "approval.create",
  "approval.review",
  "approval.approve",
  "approval.reject",
  "finance.read",
  "finance.manage",
  "employee.read",
  "employee.manage",
  "reports.management.read",
  "audit.read",
  "notification.read",
  "workflow.start",
  "workflow.advance",
  "workflow.manage",
  "settings.manage",
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const SYSTEM_ROLES = [
  "super_admin",
  "general_manager",
  "operations_manager",
  "department_manager",
  "project_manager",
  "project_engineer",
  "engineer",
  "document_controller",
  "finance_manager",
  "finance_officer",
  "hr_manager",
  "hr_officer",
  "procurement_manager",
  "procurement_officer",
  "hse_manager",
  "hse_officer",
  "quality_manager",
  "quality_officer",
  "viewer",
  "client",
  "consultant",
  "supplier",
  "subcontractor",
] as const;

export type SystemRoleCode = (typeof SYSTEM_ROLES)[number];

export const EXTERNAL_ROLES: readonly SystemRoleCode[] = [
  "client",
  "consultant",
  "supplier",
  "subcontractor",
];

export const ALL_INTERNAL_PERMISSIONS: readonly PermissionKey[] = PERMISSIONS;

const READ_PERMISSIONS: PermissionKey[] = PERMISSIONS.filter((key) =>
  key.endsWith(".read"),
);

const PROJECT_OPERATIONS: PermissionKey[] = [
  "project.create",
  "project.read",
  "project.update",
  "project.archive",
  "project.manage_team",
  "document.upload",
  "document.read",
  "document.update",
  "document.approve",
  "approval.create",
  "approval.review",
  "approval.approve",
  "approval.reject",
  "workflow.start",
  "workflow.advance",
  "workflow.manage",
  "employee.read",
  "department.read",
  "notification.read",
  "reports.management.read",
];

export const ROLE_PERMISSION_MAP: Record<SystemRoleCode, readonly PermissionKey[]> = {
  super_admin: ALL_INTERNAL_PERMISSIONS,
  general_manager: ALL_INTERNAL_PERMISSIONS.filter((key) => key !== "settings.manage"),
  operations_manager: PROJECT_OPERATIONS,
  department_manager: [
    "department.read",
    "department.update",
    "project.read",
    "project.update",
    "document.upload",
    "document.read",
    "document.update",
    "document.approve",
    "approval.create",
    "approval.review",
    "approval.approve",
    "approval.reject",
    "workflow.advance",
    "employee.read",
    "notification.read",
    "audit.read",
  ],
  project_manager: [
    "project.read",
    "project.update",
    "project.manage_team",
    "document.upload",
    "document.read",
    "document.update",
    "document.approve",
    "approval.create",
    "approval.review",
    "approval.approve",
    "approval.reject",
    "workflow.start",
    "workflow.advance",
    "employee.read",
    "department.read",
    "notification.read",
  ],
  project_engineer: [
    "project.read",
    "document.upload",
    "document.read",
    "document.update",
    "approval.create",
    "approval.review",
    "workflow.advance",
    "notification.read",
    "department.read",
  ],
  engineer: [
    "project.read",
    "document.upload",
    "document.read",
    "approval.create",
    "notification.read",
  ],
  document_controller: [
    "project.read",
    "document.upload",
    "document.read",
    "document.update",
    "document.approve",
    "approval.create",
    "approval.review",
    "workflow.advance",
    "notification.read",
  ],
  finance_manager: [
    "finance.read",
    "finance.manage",
    "project.read",
    "document.read",
    "document.upload",
    "approval.create",
    "approval.review",
    "approval.approve",
    "approval.reject",
    "employee.read",
    "notification.read",
    "reports.management.read",
    "audit.read",
  ],
  finance_officer: [
    "finance.read",
    "project.read",
    "document.read",
    "document.upload",
    "approval.create",
    "notification.read",
  ],
  hr_manager: [
    "employee.read",
    "employee.manage",
    "user.read",
    "user.update",
    "department.read",
    "notification.read",
    "audit.read",
  ],
  hr_officer: ["employee.read", "user.read", "department.read", "notification.read"],
  procurement_manager: [
    "project.read",
    "document.upload",
    "document.read",
    "document.update",
    "approval.create",
    "approval.review",
    "approval.approve",
    "notification.read",
  ],
  procurement_officer: [
    "project.read",
    "document.upload",
    "document.read",
    "approval.create",
    "notification.read",
  ],
  hse_manager: [
    "project.read",
    "document.upload",
    "document.read",
    "document.update",
    "approval.create",
    "approval.review",
    "approval.approve",
    "notification.read",
  ],
  hse_officer: [
    "project.read",
    "document.upload",
    "document.read",
    "approval.create",
    "notification.read",
  ],
  quality_manager: [
    "project.read",
    "document.upload",
    "document.read",
    "document.update",
    "approval.create",
    "approval.review",
    "approval.approve",
    "notification.read",
  ],
  quality_officer: [
    "project.read",
    "document.upload",
    "document.read",
    "approval.create",
    "notification.read",
  ],
  viewer: READ_PERMISSIONS,
  client: [],
  consultant: [],
  supplier: [],
  subcontractor: [],
};

export function isPermissionKey(value: string): value is PermissionKey {
  return (PERMISSIONS as readonly string[]).includes(value);
}
