export const PERMISSIONS = [
  "organization.read",
  "organization.update",
  "department.create",
  "department.read",
  "department.update",
  "project.create",
  "project.read",
  "project.read_all",
  "project.update",
  "project.archive",
  "project.manage_team",
  "user.create",
  "user.read",
  "user.update",
  "user.disable",
  "role.read",
  "role.assign",
  "document.upload",
  "document.read",
  "document.update",
  "document.approve",
  "approval.create",
  "approval.review",
  "approval.approve",
  "approval.reject",
  "finance.read",
  "finance.manage",
  "employee.read",
  "employee.manage",
  "reports.management.read",
  "audit.read",
  "notification.read",
  "workflow.start",
  "workflow.advance",
  "workflow.manage",
  "settings.manage",
  "engineering.read",
  "engineering.manage",
  "document_control.read",
  "document_control.register",
  "document_control.submit",
  "document_control.revise",
  "rfi.create",
  "rfi.read",
  "rfi.update",
  "rfi.submit",
  "rfi.respond",
  "rfi.close",
  "submittal.create",
  "submittal.read",
  "submittal.update",
  "submittal.submit",
  "shop_drawing.create",
  "shop_drawing.read",
  "shop_drawing.update",
  "shop_drawing.submit",
  "method_statement.create",
  "method_statement.read",
  "method_statement.update",
  "method_statement.submit",
  "inspection.create",
  "inspection.read",
  "inspection.perform",
  "inspection.close",
  "ncr.create",
  "ncr.read",
  "ncr.manage",
  "ncr.close",
  "report.create",
  "report.read",
  "report.approve",
  "correspondence.create",
  "correspondence.read",
  "correspondence.manage",
  "transmittal.create",
  "transmittal.read",
  "transmittal.issue",
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const SYSTEM_ROLES = [
  "super_admin",
  "general_manager",
  "operations_manager",
  "department_manager",
  "project_manager",
  "project_engineer",
  "engineer",
  "document_controller",
  "finance_manager",
  "finance_officer",
  "hr_manager",
  "hr_officer",
  "procurement_manager",
  "procurement_officer",
  "hse_manager",
  "hse_officer",
  "quality_manager",
  "quality_officer",
  "viewer",
  "client",
  "consultant",
  "supplier",
  "subcontractor",
] as const;

export type SystemRoleCode = (typeof SYSTEM_ROLES)[number];

export const EXTERNAL_ROLES: readonly SystemRoleCode[] = [
  "client",
  "consultant",
  "supplier",
  "subcontractor",
];

export const ALL_INTERNAL_PERMISSIONS: readonly PermissionKey[] = PERMISSIONS;

/** Viewer: limited Phase 1 reads only — not every *.read permission. */
const VIEWER_PERMISSIONS: PermissionKey[] = [
  "organization.read",
  "department.read",
  "project.read",
  "document.read",
  "notification.read",
];

const PHASE2_OPS: PermissionKey[] = [
  "engineering.read",
  "engineering.manage",
  "document_control.read",
  "document_control.submit",
  "rfi.create",
  "rfi.read",
  "rfi.update",
  "rfi.submit",
  "rfi.respond",
  "rfi.close",
  "submittal.create",
  "submittal.read",
  "submittal.update",
  "submittal.submit",
  "shop_drawing.create",
  "shop_drawing.read",
  "shop_drawing.update",
  "shop_drawing.submit",
  "method_statement.create",
  "method_statement.read",
  "method_statement.update",
  "method_statement.submit",
  "inspection.create",
  "inspection.read",
  "inspection.perform",
  "inspection.close",
  "ncr.create",
  "ncr.read",
  "ncr.manage",
  "ncr.close",
  "report.create",
  "report.read",
  "report.approve",
  "correspondence.create",
  "correspondence.read",
  "correspondence.manage",
  "transmittal.create",
  "transmittal.read",
  "transmittal.issue",
];

export const ROLE_PERMISSION_MAP: Record<SystemRoleCode, readonly PermissionKey[]> = {
  super_admin: ALL_INTERNAL_PERMISSIONS,
  general_manager: ALL_INTERNAL_PERMISSIONS.filter((key) => key !== "settings.manage"),
  operations_manager: [
    "project.create",
    "project.read",
    "project.read_all",
    "project.update",
    "project.archive",
    "project.manage_team",
    "document.upload",
    "document.read",
    "document.update",
    "document.approve",
    "approval.create",
    "approval.review",
    "approval.approve",
    "approval.reject",
    "workflow.start",
    "workflow.advance",
    "workflow.manage",
    "employee.read",
    "department.read",
    "notification.read",
    "reports.management.read",
    ...PHASE2_OPS,
  ],
  department_manager: [
    "department.read",
    "department.update",
    "project.read",
    "project.update",
    "document.upload",
    "document.read",
    "document.update",
    "document.approve",
    "approval.create",
    "approval.review",
    "approval.approve",
    "approval.reject",
    "workflow.advance",
    "employee.read",
    "notification.read",
    "audit.read",
    "engineering.read",
    "rfi.read",
    "submittal.read",
    "shop_drawing.read",
    "method_statement.read",
    "inspection.read",
    "ncr.read",
  ],
  project_manager: [
    "project.read",
    "project.update",
    "project.manage_team",
    "document.upload",
    "document.read",
    "document.update",
    "document.approve",
    "approval.create",
    "approval.review",
    "approval.approve",
    "approval.reject",
    "workflow.start",
    "workflow.advance",
    "employee.read",
    "department.read",
    "notification.read",
    ...PHASE2_OPS,
  ],
  project_engineer: [
    "project.read",
    "document.upload",
    "document.read",
    "document.update",
    "approval.create",
    "approval.review",
    "workflow.advance",
    "notification.read",
    "department.read",
    "engineering.read",
    "rfi.create",
    "rfi.read",
    "rfi.update",
    "rfi.submit",
    "submittal.create",
    "submittal.read",
    "submittal.update",
    "submittal.submit",
    "shop_drawing.create",
    "shop_drawing.read",
    "shop_drawing.update",
    "shop_drawing.submit",
    "method_statement.create",
    "method_statement.read",
    "method_statement.update",
    "inspection.create",
    "inspection.read",
    "inspection.perform",
    "ncr.create",
    "ncr.read",
    "report.create",
    "report.read",
    "correspondence.read",
  ],
  engineer: [
    "project.read",
    "document.upload",
    "document.read",
    "approval.create",
    "notification.read",
    "engineering.read",
    "rfi.create",
    "rfi.read",
    "rfi.update",
    "submittal.create",
    "submittal.read",
    "submittal.update",
    "shop_drawing.create",
    "shop_drawing.read",
    "shop_drawing.update",
    "method_statement.create",
    "method_statement.read",
    "inspection.create",
    "inspection.read",
    "ncr.create",
    "ncr.read",
    "report.create",
    "report.read",
  ],
  document_controller: [
    "project.read",
    "project.read_all",
    "document.upload",
    "document.read",
    "document.update",
    "document.approve",
    "approval.create",
    "approval.review",
    "workflow.advance",
    "notification.read",
    "engineering.read",
    "document_control.read",
    "document_control.register",
    "document_control.submit",
    "document_control.revise",
    "rfi.read",
    "rfi.submit",
    "submittal.read",
    "submittal.submit",
    "shop_drawing.read",
    "shop_drawing.submit",
    "method_statement.read",
    "method_statement.submit",
    "inspection.read",
    "ncr.read",
    "report.read",
    "correspondence.create",
    "correspondence.read",
    "correspondence.manage",
    "transmittal.create",
    "transmittal.read",
    "transmittal.issue",
  ],
  finance_manager: [
    "finance.read",
    "finance.manage",
    "project.read",
    "project.read_all",
    "document.read",
    "document.upload",
    "approval.create",
    "approval.review",
    "approval.approve",
    "approval.reject",
    "employee.read",
    "notification.read",
    "reports.management.read",
    "audit.read",
  ],
  finance_officer: [
    "finance.read",
    "project.read",
    "document.read",
    "document.upload",
    "approval.create",
    "notification.read",
  ],
  hr_manager: [
    "employee.read",
    "employee.manage",
    "user.read",
    "user.update",
    "department.read",
    "notification.read",
    "audit.read",
  ],
  hr_officer: ["employee.read", "user.read", "department.read", "notification.read"],
  procurement_manager: [
    "project.read",
    "document.upload",
    "document.read",
    "document.update",
    "approval.create",
    "approval.review",
    "approval.approve",
    "notification.read",
  ],
  procurement_officer: [
    "project.read",
    "document.upload",
    "document.read",
    "approval.create",
    "notification.read",
  ],
  hse_manager: [
    "project.read",
    "document.upload",
    "document.read",
    "document.update",
    "approval.create",
    "approval.review",
    "approval.approve",
    "notification.read",
    "engineering.read",
    "method_statement.read",
    "inspection.read",
    "ncr.read",
  ],
  hse_officer: [
    "project.read",
    "document.upload",
    "document.read",
    "approval.create",
    "notification.read",
    "method_statement.read",
    "inspection.read",
  ],
  quality_manager: [
    "project.read",
    "project.read_all",
    "document.upload",
    "document.read",
    "document.update",
    "approval.create",
    "approval.review",
    "approval.approve",
    "notification.read",
    "engineering.read",
    "inspection.create",
    "inspection.read",
    "inspection.perform",
    "inspection.close",
    "ncr.create",
    "ncr.read",
    "ncr.manage",
    "ncr.close",
    "method_statement.read",
  ],
  quality_officer: [
    "project.read",
    "document.upload",
    "document.read",
    "approval.create",
    "notification.read",
    "engineering.read",
    "inspection.create",
    "inspection.read",
    "inspection.perform",
    "ncr.create",
    "ncr.read",
  ],
  viewer: VIEWER_PERMISSIONS,
  client: [],
  consultant: [],
  supplier: [],
  subcontractor: [],
};

export function isPermissionKey(value: string): value is PermissionKey {
  return (PERMISSIONS as readonly string[]).includes(value);
}
