export const DOMAIN_EVENTS = [
  "project.created",
  "project.updated",
  "project.archived",
  "project.stage.started",
  "project.stage.completed",
  "project.member.assigned",
  "project.health_changed",
  "approval.created",
  "approval.overdue",
  "approval.approved",
  "approval.rejected",
  "approval.resubmitted",
  "document.uploaded",
  "document.registered",
  "document.revised",
  "document.submitted",
  "document.approved",
  "document.resubmit_required",
  "document.rejected",
  "workflow.started",
  "workflow.step.completed",
  "workflow.cancelled",
  "employee.created",
  "employee.assigned",
  "employee.deactivated",
  "user.role.changed",
  "user.deactivated",
  "rfi.created",
  "rfi.submitted",
  "rfi.answered",
  "rfi.overdue",
  "inspection.submitted",
  "inspection.failed",
  "inspection.passed",
  "ncr.created",
  "ncr.critical",
  "ncr.closed",
  "ncr.reopened",
  "transmittal.issued",
  "purchase_request.created",
  "purchase_request.approved",
  "purchase_request.rejected",
  "rfq.issued",
  "rfq.response_due",
  "quotation.received",
  "purchase_order.approved",
  "purchase_order.issued",
  "purchase_order.delivery_due",
  "goods_receipt.received",
  "goods_receipt.rejected",
  "supplier_invoice.received",
  "supplier_invoice.discrepancy",
  "supplier_invoice.due_soon",
  "supplier_invoice.overdue",
  "supplier_payment.recorded",
  "client_valuation.submitted",
  "client_valuation.certified",
  "client_invoice.issued",
  "client_invoice.overdue",
  "client_payment.received",
  "variation.submitted",
  "variation.approved",
  "variation.partially_approved",
  "variation.rejected",
  "project.budget_warning",
  "project.margin_warning",
  "project.cashflow_warning",
] as const;

export type DomainEventType = (typeof DOMAIN_EVENTS)[number];

export type DomainEvent<TPayload extends Record<string, unknown> = Record<string, unknown>> = {
  type: DomainEventType;
  organizationId: string;
  actorId: string | null;
  entityType: string;
  entityId: string;
  payload: TPayload;
  correlationId: string;
  occurredAt: string;
};
