export const COMMERCIAL_STATUS_AR: Record<string, string> = {
  draft: "مسودة",
  submitted: "مقدّم",
  under_review: "قيد المراجعة",
  approved: "معتمد",
  rejected: "مرفوض",
  cancelled: "ملغى",
  converted_to_rfq: "محوّل إلى طلب عرض",
  ready_to_issue: "جاهز للإصدار",
  issued: "صادر",
  responses_received: "وردت الردود",
  under_comparison: "قيد المقارنة",
  awarded: "مرسّى",
  closed: "مغلق",
  invited: "مدعو",
  acknowledged: "تم الإقرار",
  responded: "تم الرد",
  declined: "اعتذار",
  no_response: "بدون رد",
  pending_approval: "بانتظار الاعتماد",
  recommended: "موصى به",
  open: "مفتوح",
  partially_delivered: "تسليم جزئي",
  delivered: "مُسلّم",
  partially_invoiced: "فوترة جزئية",
  invoiced: "مفوتر",
  received: "مستلم",
  partially_accepted: "قبول جزئي",
  accepted: "مقبول",
  matched: "مطابق",
  discrepancy: "اختلاف",
  approved_for_payment: "معتمد للدفع",
  partially_paid: "مدفوع جزئياً",
  paid: "مدفوع",
  low: "منخفض",
  medium: "متوسط",
  high: "مرتفع",
  critical: "حرج",
  active: "نشط",
  suspended: "موقوف",
  blocked: "محظور",
  archived: "مؤرشف",
  internal_review: "مراجعة داخلية",
  under_client_review: "قيد مراجعة العميل",
  partially_certified: "معتمد جزئياً",
  eligible: "مؤهل للمطالبة",
  partially_approved: "معتمد جزئياً",
  negotiation: "تفاوض",
  terminated: "منتهٍ",
  completed: "مكتمل",
  overdue: "متأخر",
  certified: "معتمد من العميل",
  planned: "مخطط",
  claimed: "مُطالب",
};

export function commercialStatusLabel(status: string): string {
  return COMMERCIAL_STATUS_AR[status] ?? status.replaceAll("_", " ");
}
