-- Master Touch OS — 025
-- Phase 2 RBAC permissions, role mappings, and project.read_all for org-wide access.

insert into public.permissions (key, resource, action, description_ar, description_en) values
  ('project.read_all', 'project', 'read_all', 'عرض جميع مشاريع المنشأة', 'Read all organization projects'),
  ('engineering.read', 'engineering', 'read', 'عرض الهندسة', 'Read engineering'),
  ('engineering.manage', 'engineering', 'manage', 'إدارة الهندسة', 'Manage engineering'),
  ('document_control.read', 'document_control', 'read', 'عرض مراقبة الوثائق', 'Read document control'),
  ('document_control.register', 'document_control', 'register', 'تسجيل وثيقة', 'Register document'),
  ('document_control.submit', 'document_control', 'submit', 'إصدار وثيقة', 'Submit document'),
  ('document_control.revise', 'document_control', 'revise', 'إنشاء مراجعة', 'Revise document'),
  ('rfi.create', 'rfi', 'create', 'إنشاء طلب استفسار', 'Create RFI'),
  ('rfi.read', 'rfi', 'read', 'عرض طلبات الاستفسار', 'Read RFI'),
  ('rfi.update', 'rfi', 'update', 'تحديث طلب استفسار', 'Update RFI'),
  ('rfi.submit', 'rfi', 'submit', 'تقديم طلب استفسار', 'Submit RFI'),
  ('rfi.respond', 'rfi', 'respond', 'الرد على طلب استفسار', 'Respond to RFI'),
  ('rfi.close', 'rfi', 'close', 'إغلاق طلب استفسار', 'Close RFI'),
  ('submittal.create', 'submittal', 'create', 'إنشاء اعتماد مواد', 'Create material submittal'),
  ('submittal.read', 'submittal', 'read', 'عرض اعتماد المواد', 'Read material submittal'),
  ('submittal.update', 'submittal', 'update', 'تحديث اعتماد مواد', 'Update material submittal'),
  ('submittal.submit', 'submittal', 'submit', 'تقديم اعتماد مواد', 'Submit material submittal'),
  ('shop_drawing.create', 'shop_drawing', 'create', 'إنشاء مخطط تنفيذي', 'Create shop drawing'),
  ('shop_drawing.read', 'shop_drawing', 'read', 'عرض المخططات التنفيذية', 'Read shop drawing'),
  ('shop_drawing.update', 'shop_drawing', 'update', 'تحديث مخطط تنفيذي', 'Update shop drawing'),
  ('shop_drawing.submit', 'shop_drawing', 'submit', 'تقديم مخطط تنفيذي', 'Submit shop drawing'),
  ('method_statement.create', 'method_statement', 'create', 'إنشاء طريقة تنفيذ', 'Create method statement'),
  ('method_statement.read', 'method_statement', 'read', 'عرض طرق التنفيذ', 'Read method statement'),
  ('method_statement.update', 'method_statement', 'update', 'تحديث طريقة تنفيذ', 'Update method statement'),
  ('method_statement.submit', 'method_statement', 'submit', 'تقديم طريقة تنفيذ', 'Submit method statement'),
  ('inspection.create', 'inspection', 'create', 'إنشاء طلب فحص', 'Create inspection request'),
  ('inspection.read', 'inspection', 'read', 'عرض طلبات الفحص', 'Read inspection'),
  ('inspection.perform', 'inspection', 'perform', 'تنفيذ فحص', 'Perform inspection'),
  ('inspection.close', 'inspection', 'close', 'إغلاق طلب فحص', 'Close inspection'),
  ('ncr.create', 'ncr', 'create', 'إنشاء تقرير عدم مطابقة', 'Create NCR'),
  ('ncr.read', 'ncr', 'read', 'عرض تقارير عدم المطابقة', 'Read NCR'),
  ('ncr.manage', 'ncr', 'manage', 'إدارة تقرير عدم مطابقة', 'Manage NCR'),
  ('ncr.close', 'ncr', 'close', 'إغلاق تقرير عدم مطابقة', 'Close NCR'),
  ('report.create', 'report', 'create', 'إنشاء تقرير مشروع', 'Create project report'),
  ('report.read', 'report', 'read', 'عرض تقارير المشروع', 'Read project report'),
  ('report.approve', 'report', 'approve', 'اعتماد تقرير مشروع', 'Approve project report'),
  ('correspondence.create', 'correspondence', 'create', 'إنشاء مراسلة', 'Create correspondence'),
  ('correspondence.read', 'correspondence', 'read', 'عرض المراسلات', 'Read correspondence'),
  ('correspondence.manage', 'correspondence', 'manage', 'إدارة المراسلات', 'Manage correspondence'),
  ('transmittal.create', 'transmittal', 'create', 'إنشاء إرسالية', 'Create transmittal'),
  ('transmittal.read', 'transmittal', 'read', 'عرض الإرساليات', 'Read transmittal'),
  ('transmittal.issue', 'transmittal', 'issue', 'إصدار إرسالية', 'Issue transmittal')
on conflict (key) do nothing;

-- Org-wide project visibility
insert into public.role_permissions (role_id, permission_key)
select r.id, 'project.read_all'
from public.roles r
where r.code in (
  'super_admin', 'general_manager', 'operations_manager',
  'document_controller', 'quality_manager', 'finance_manager'
)
on conflict do nothing;

-- Engineering / DC / module permissions by role
insert into public.role_permissions (role_id, permission_key)
select r.id, p.key
from public.roles r
cross join public.permissions p
where r.code = 'super_admin'
  and p.key in (
    select key from public.permissions
    where key like 'engineering.%'
       or key like 'document_control.%'
       or key like 'rfi.%'
       or key like 'submittal.%'
       or key like 'shop_drawing.%'
       or key like 'method_statement.%'
       or key like 'inspection.%'
       or key like 'ncr.%'
       or key like 'report.%'
       or key like 'correspondence.%'
       or key like 'transmittal.%'
       or key = 'project.read_all'
  )
on conflict do nothing;

insert into public.role_permissions (role_id, permission_key)
select r.id, x.permission_key
from public.roles r
join (values
  ('general_manager', 'project.read_all'),
  ('general_manager', 'engineering.read'),
  ('general_manager', 'engineering.manage'),
  ('general_manager', 'document_control.read'),
  ('general_manager', 'rfi.read'),
  ('general_manager', 'submittal.read'),
  ('general_manager', 'shop_drawing.read'),
  ('general_manager', 'method_statement.read'),
  ('general_manager', 'inspection.read'),
  ('general_manager', 'ncr.read'),
  ('general_manager', 'ncr.manage'),
  ('general_manager', 'report.read'),
  ('general_manager', 'correspondence.read'),
  ('general_manager', 'transmittal.read'),
  ('operations_manager', 'project.read_all'),
  ('operations_manager', 'engineering.read'),
  ('operations_manager', 'engineering.manage'),
  ('operations_manager', 'document_control.read'),
  ('operations_manager', 'document_control.submit'),
  ('operations_manager', 'rfi.create'),
  ('operations_manager', 'rfi.read'),
  ('operations_manager', 'rfi.update'),
  ('operations_manager', 'rfi.submit'),
  ('operations_manager', 'rfi.close'),
  ('operations_manager', 'submittal.create'),
  ('operations_manager', 'submittal.read'),
  ('operations_manager', 'submittal.submit'),
  ('operations_manager', 'shop_drawing.create'),
  ('operations_manager', 'shop_drawing.read'),
  ('operations_manager', 'shop_drawing.submit'),
  ('operations_manager', 'method_statement.create'),
  ('operations_manager', 'method_statement.read'),
  ('operations_manager', 'method_statement.submit'),
  ('operations_manager', 'inspection.create'),
  ('operations_manager', 'inspection.read'),
  ('operations_manager', 'inspection.perform'),
  ('operations_manager', 'ncr.create'),
  ('operations_manager', 'ncr.read'),
  ('operations_manager', 'ncr.manage'),
  ('operations_manager', 'report.create'),
  ('operations_manager', 'report.read'),
  ('operations_manager', 'correspondence.create'),
  ('operations_manager', 'correspondence.read'),
  ('operations_manager', 'transmittal.create'),
  ('operations_manager', 'transmittal.read'),
  ('operations_manager', 'transmittal.issue'),
  ('project_manager', 'engineering.read'),
  ('project_manager', 'engineering.manage'),
  ('project_manager', 'document_control.read'),
  ('project_manager', 'document_control.register'),
  ('project_manager', 'document_control.submit'),
  ('project_manager', 'document_control.revise'),
  ('project_manager', 'document.approve'),
  ('project_manager', 'rfi.create'),
  ('project_manager', 'rfi.read'),
  ('project_manager', 'rfi.update'),
  ('project_manager', 'rfi.submit'),
  ('project_manager', 'rfi.respond'),
  ('project_manager', 'rfi.close'),
  ('project_manager', 'submittal.create'),
  ('project_manager', 'submittal.read'),
  ('project_manager', 'submittal.update'),
  ('project_manager', 'submittal.submit'),
  ('project_manager', 'shop_drawing.create'),
  ('project_manager', 'shop_drawing.read'),
  ('project_manager', 'shop_drawing.update'),
  ('project_manager', 'shop_drawing.submit'),
  ('project_manager', 'method_statement.create'),
  ('project_manager', 'method_statement.read'),
  ('project_manager', 'method_statement.update'),
  ('project_manager', 'method_statement.submit'),
  ('project_manager', 'inspection.create'),
  ('project_manager', 'inspection.read'),
  ('project_manager', 'inspection.perform'),
  ('project_manager', 'inspection.close'),
  ('project_manager', 'ncr.create'),
  ('project_manager', 'ncr.read'),
  ('project_manager', 'ncr.manage'),
  ('project_manager', 'ncr.close'),
  ('project_manager', 'report.create'),
  ('project_manager', 'report.read'),
  ('project_manager', 'report.approve'),
  ('project_manager', 'correspondence.create'),
  ('project_manager', 'correspondence.read'),
  ('project_manager', 'correspondence.manage'),
  ('project_manager', 'transmittal.create'),
  ('project_manager', 'transmittal.read'),
  ('project_manager', 'transmittal.issue'),
  ('project_engineer', 'engineering.read'),
  ('project_engineer', 'document_control.read'),
  ('project_engineer', 'rfi.create'),
  ('project_engineer', 'rfi.read'),
  ('project_engineer', 'rfi.update'),
  ('project_engineer', 'rfi.submit'),
  ('project_engineer', 'submittal.create'),
  ('project_engineer', 'submittal.read'),
  ('project_engineer', 'submittal.update'),
  ('project_engineer', 'submittal.submit'),
  ('project_engineer', 'shop_drawing.create'),
  ('project_engineer', 'shop_drawing.read'),
  ('project_engineer', 'shop_drawing.update'),
  ('project_engineer', 'shop_drawing.submit'),
  ('project_engineer', 'method_statement.create'),
  ('project_engineer', 'method_statement.read'),
  ('project_engineer', 'method_statement.update'),
  ('project_engineer', 'inspection.create'),
  ('project_engineer', 'inspection.read'),
  ('project_engineer', 'inspection.perform'),
  ('project_engineer', 'ncr.create'),
  ('project_engineer', 'ncr.read'),
  ('project_engineer', 'report.create'),
  ('project_engineer', 'report.read'),
  ('project_engineer', 'correspondence.read'),
  ('engineer', 'engineering.read'),
  ('engineer', 'rfi.create'),
  ('engineer', 'rfi.read'),
  ('engineer', 'rfi.update'),
  ('engineer', 'submittal.create'),
  ('engineer', 'submittal.read'),
  ('engineer', 'submittal.update'),
  ('engineer', 'shop_drawing.create'),
  ('engineer', 'shop_drawing.read'),
  ('engineer', 'shop_drawing.update'),
  ('engineer', 'method_statement.create'),
  ('engineer', 'method_statement.read'),
  ('engineer', 'inspection.create'),
  ('engineer', 'inspection.read'),
  ('engineer', 'ncr.create'),
  ('engineer', 'ncr.read'),
  ('engineer', 'report.create'),
  ('engineer', 'report.read'),
  ('document_controller', 'project.read_all'),
  ('document_controller', 'engineering.read'),
  ('document_controller', 'document_control.read'),
  ('document_controller', 'document_control.register'),
  ('document_controller', 'document_control.submit'),
  ('document_controller', 'document_control.revise'),
  ('document_controller', 'rfi.read'),
  ('document_controller', 'rfi.submit'),
  ('document_controller', 'submittal.read'),
  ('document_controller', 'submittal.submit'),
  ('document_controller', 'shop_drawing.read'),
  ('document_controller', 'shop_drawing.submit'),
  ('document_controller', 'method_statement.read'),
  ('document_controller', 'method_statement.submit'),
  ('document_controller', 'inspection.read'),
  ('document_controller', 'ncr.read'),
  ('document_controller', 'report.read'),
  ('document_controller', 'correspondence.create'),
  ('document_controller', 'correspondence.read'),
  ('document_controller', 'correspondence.manage'),
  ('document_controller', 'transmittal.create'),
  ('document_controller', 'transmittal.read'),
  ('document_controller', 'transmittal.issue'),
  ('quality_manager', 'project.read_all'),
  ('quality_manager', 'engineering.read'),
  ('quality_manager', 'inspection.create'),
  ('quality_manager', 'inspection.read'),
  ('quality_manager', 'inspection.perform'),
  ('quality_manager', 'inspection.close'),
  ('quality_manager', 'ncr.create'),
  ('quality_manager', 'ncr.read'),
  ('quality_manager', 'ncr.manage'),
  ('quality_manager', 'ncr.close'),
  ('quality_manager', 'method_statement.read'),
  ('quality_officer', 'engineering.read'),
  ('quality_officer', 'inspection.create'),
  ('quality_officer', 'inspection.read'),
  ('quality_officer', 'inspection.perform'),
  ('quality_officer', 'ncr.create'),
  ('quality_officer', 'ncr.read'),
  ('hse_manager', 'engineering.read'),
  ('hse_manager', 'method_statement.read'),
  ('hse_manager', 'inspection.read'),
  ('hse_manager', 'ncr.read'),
  ('hse_officer', 'method_statement.read'),
  ('hse_officer', 'inspection.read')
) as x(code, permission_key) on x.code = r.code
on conflict do nothing;
