-- Master Touch OS — 042
-- Phase 3 RBAC permissions and role mappings.

insert into public.permissions (key, resource, action, description_ar, description_en) values
  ('supplier.read', 'supplier', 'read', 'عرض الموردين', 'Read suppliers'),
  ('supplier.manage', 'supplier', 'manage', 'إدارة الموردين', 'Manage suppliers'),
  ('procurement.read', 'procurement', 'read', 'عرض المشتريات', 'Read procurement'),
  ('procurement.manage', 'procurement', 'manage', 'إدارة المشتريات', 'Manage procurement'),
  ('purchase_request.create', 'purchase_request', 'create', 'إنشاء طلب شراء', 'Create purchase request'),
  ('purchase_request.read', 'purchase_request', 'read', 'عرض طلبات الشراء', 'Read purchase request'),
  ('purchase_request.approve', 'purchase_request', 'approve', 'اعتماد طلب شراء', 'Approve purchase request'),
  ('rfq.create', 'rfq', 'create', 'إنشاء طلب عرض سعر', 'Create RFQ'),
  ('rfq.read', 'rfq', 'read', 'عرض طلبات عروض الأسعار', 'Read RFQ'),
  ('rfq.issue', 'rfq', 'issue', 'إصدار طلب عرض سعر', 'Issue RFQ'),
  ('rfq.manage', 'rfq', 'manage', 'إدارة طلبات عروض الأسعار', 'Manage RFQ'),
  ('quotation.create', 'quotation', 'create', 'تسجيل عرض سعر', 'Create quotation'),
  ('quotation.read', 'quotation', 'read', 'عرض عروض الأسعار', 'Read quotation'),
  ('quotation.compare', 'quotation', 'compare', 'مقارنة عروض الأسعار', 'Compare quotations'),
  ('quotation.recommend', 'quotation', 'recommend', 'توصية مورد', 'Recommend quotation'),
  ('purchase_order.create', 'purchase_order', 'create', 'إنشاء أمر شراء', 'Create purchase order'),
  ('purchase_order.read', 'purchase_order', 'read', 'عرض أوامر الشراء', 'Read purchase order'),
  ('purchase_order.approve', 'purchase_order', 'approve', 'اعتماد أمر شراء', 'Approve purchase order'),
  ('purchase_order.issue', 'purchase_order', 'issue', 'إصدار أمر شراء', 'Issue purchase order'),
  ('goods_receipt.create', 'goods_receipt', 'create', 'إنشاء استلام مواد', 'Create goods receipt'),
  ('goods_receipt.read', 'goods_receipt', 'read', 'عرض استلام المواد', 'Read goods receipt'),
  ('goods_receipt.manage', 'goods_receipt', 'manage', 'إدارة استلام المواد', 'Manage goods receipt'),
  ('supplier_invoice.create', 'supplier_invoice', 'create', 'تسجيل فاتورة مورد', 'Create supplier invoice'),
  ('supplier_invoice.read', 'supplier_invoice', 'read', 'عرض فواتير الموردين', 'Read supplier invoice'),
  ('supplier_invoice.review', 'supplier_invoice', 'review', 'مراجعة فاتورة مورد', 'Review supplier invoice'),
  ('supplier_invoice.approve', 'supplier_invoice', 'approve', 'اعتماد فاتورة مورد للصرف', 'Approve supplier invoice'),
  ('supplier_payment.read', 'supplier_payment', 'read', 'عرض دفعات الموردين', 'Read supplier payment'),
  ('supplier_payment.record', 'supplier_payment', 'record', 'تسجيل دفعة مورد', 'Record supplier payment'),
  ('supplier_payment.approve', 'supplier_payment', 'approve', 'اعتماد دفعة مورد', 'Approve supplier payment'),
  ('project_budget.read', 'project_budget', 'read', 'عرض ميزانية المشروع', 'Read project budget'),
  ('project_budget.manage', 'project_budget', 'manage', 'إدارة ميزانية المشروع', 'Manage project budget'),
  ('client_valuation.create', 'client_valuation', 'create', 'إنشاء مستخلص', 'Create client valuation'),
  ('client_valuation.read', 'client_valuation', 'read', 'عرض المستخلصات', 'Read client valuation'),
  ('client_valuation.submit', 'client_valuation', 'submit', 'تقديم مستخلص', 'Submit client valuation'),
  ('client_valuation.approve', 'client_valuation', 'approve', 'اعتماد مستخلص', 'Approve client valuation'),
  ('client_invoice.create', 'client_invoice', 'create', 'إنشاء فاتورة عميل', 'Create client invoice'),
  ('client_invoice.read', 'client_invoice', 'read', 'عرض فواتير العملاء', 'Read client invoice'),
  ('client_invoice.issue', 'client_invoice', 'issue', 'إصدار فاتورة عميل', 'Issue client invoice'),
  ('client_payment.read', 'client_payment', 'read', 'عرض مقبوضات العملاء', 'Read client payment'),
  ('client_payment.record', 'client_payment', 'record', 'تسجيل مقبوض عميل', 'Record client payment'),
  ('variation.create', 'variation', 'create', 'إنشاء أمر تغيير', 'Create variation'),
  ('variation.read', 'variation', 'read', 'عرض أوامر التغيير', 'Read variation'),
  ('variation.submit', 'variation', 'submit', 'تقديم أمر تغيير', 'Submit variation'),
  ('variation.approve', 'variation', 'approve', 'اعتماد أمر تغيير', 'Approve variation'),
  ('commercial_reports.read', 'commercial_reports', 'read', 'عرض التقارير التجارية', 'Read commercial reports')
on conflict (key) do nothing;

insert into public.role_permissions (role_id, permission_key)
select r.id, p.key
from public.roles r
cross join public.permissions p
where r.code = 'super_admin'
  and (
    p.key like 'supplier.%'
    or p.key like 'procurement.%'
    or p.key like 'purchase_request.%'
    or p.key like 'rfq.%'
    or p.key like 'quotation.%'
    or p.key like 'purchase_order.%'
    or p.key like 'goods_receipt.%'
    or p.key like 'supplier_invoice.%'
    or p.key like 'supplier_payment.%'
    or p.key like 'project_budget.%'
    or p.key like 'client_valuation.%'
    or p.key like 'client_invoice.%'
    or p.key like 'client_payment.%'
    or p.key like 'variation.%'
    or p.key = 'commercial_reports.read'
    or p.key in ('finance.read', 'finance.manage')
  )
on conflict do nothing;

insert into public.role_permissions (role_id, permission_key)
select r.id, x.permission_key
from public.roles r
join (values
  ('general_manager', 'supplier.read'),
  ('general_manager', 'procurement.read'),
  ('general_manager', 'purchase_request.read'),
  ('general_manager', 'purchase_request.approve'),
  ('general_manager', 'rfq.read'),
  ('general_manager', 'quotation.read'),
  ('general_manager', 'purchase_order.read'),
  ('general_manager', 'purchase_order.approve'),
  ('general_manager', 'supplier_invoice.read'),
  ('general_manager', 'supplier_invoice.approve'),
  ('general_manager', 'supplier_payment.read'),
  ('general_manager', 'supplier_payment.approve'),
  ('general_manager', 'project_budget.read'),
  ('general_manager', 'finance.read'),
  ('general_manager', 'finance.manage'),
  ('general_manager', 'client_valuation.read'),
  ('general_manager', 'client_valuation.approve'),
  ('general_manager', 'client_invoice.read'),
  ('general_manager', 'client_payment.read'),
  ('general_manager', 'variation.read'),
  ('general_manager', 'variation.approve'),
  ('general_manager', 'commercial_reports.read'),
  ('operations_manager', 'supplier.read'),
  ('operations_manager', 'procurement.read'),
  ('operations_manager', 'procurement.manage'),
  ('operations_manager', 'purchase_request.read'),
  ('operations_manager', 'purchase_request.approve'),
  ('operations_manager', 'rfq.read'),
  ('operations_manager', 'rfq.manage'),
  ('operations_manager', 'quotation.read'),
  ('operations_manager', 'purchase_order.read'),
  ('operations_manager', 'purchase_order.approve'),
  ('operations_manager', 'goods_receipt.read'),
  ('operations_manager', 'project_budget.read'),
  ('operations_manager', 'finance.read'),
  ('operations_manager', 'variation.read'),
  ('operations_manager', 'commercial_reports.read'),
  ('project_manager', 'supplier.read'),
  ('project_manager', 'procurement.read'),
  ('project_manager', 'purchase_request.create'),
  ('project_manager', 'purchase_request.read'),
  ('project_manager', 'purchase_request.approve'),
  ('project_manager', 'rfq.read'),
  ('project_manager', 'quotation.read'),
  ('project_manager', 'quotation.compare'),
  ('project_manager', 'purchase_order.read'),
  ('project_manager', 'purchase_order.approve'),
  ('project_manager', 'goods_receipt.read'),
  ('project_manager', 'supplier_invoice.read'),
  ('project_manager', 'project_budget.read'),
  ('project_manager', 'client_valuation.create'),
  ('project_manager', 'client_valuation.read'),
  ('project_manager', 'client_valuation.submit'),
  ('project_manager', 'client_invoice.read'),
  ('project_manager', 'variation.create'),
  ('project_manager', 'variation.read'),
  ('project_manager', 'variation.submit'),
  ('project_manager', 'commercial_reports.read'),
  ('project_engineer', 'purchase_request.create'),
  ('project_engineer', 'purchase_request.read'),
  ('project_engineer', 'rfq.read'),
  ('project_engineer', 'goods_receipt.read'),
  ('project_engineer', 'variation.create'),
  ('project_engineer', 'variation.read'),
  ('engineer', 'purchase_request.create'),
  ('engineer', 'purchase_request.read'),
  ('engineer', 'goods_receipt.create'),
  ('engineer', 'goods_receipt.read'),
  ('procurement_manager', 'supplier.read'),
  ('procurement_manager', 'supplier.manage'),
  ('procurement_manager', 'procurement.read'),
  ('procurement_manager', 'procurement.manage'),
  ('procurement_manager', 'purchase_request.read'),
  ('procurement_manager', 'purchase_request.approve'),
  ('procurement_manager', 'rfq.create'),
  ('procurement_manager', 'rfq.read'),
  ('procurement_manager', 'rfq.issue'),
  ('procurement_manager', 'rfq.manage'),
  ('procurement_manager', 'quotation.create'),
  ('procurement_manager', 'quotation.read'),
  ('procurement_manager', 'quotation.compare'),
  ('procurement_manager', 'quotation.recommend'),
  ('procurement_manager', 'purchase_order.create'),
  ('procurement_manager', 'purchase_order.read'),
  ('procurement_manager', 'purchase_order.approve'),
  ('procurement_manager', 'purchase_order.issue'),
  ('procurement_manager', 'goods_receipt.create'),
  ('procurement_manager', 'goods_receipt.read'),
  ('procurement_manager', 'goods_receipt.manage'),
  ('procurement_manager', 'supplier_invoice.read'),
  ('procurement_manager', 'supplier_invoice.review'),
  ('procurement_officer', 'supplier.read'),
  ('procurement_officer', 'procurement.read'),
  ('procurement_officer', 'purchase_request.read'),
  ('procurement_officer', 'rfq.create'),
  ('procurement_officer', 'rfq.read'),
  ('procurement_officer', 'rfq.issue'),
  ('procurement_officer', 'quotation.create'),
  ('procurement_officer', 'quotation.read'),
  ('procurement_officer', 'quotation.compare'),
  ('procurement_officer', 'purchase_order.create'),
  ('procurement_officer', 'purchase_order.read'),
  ('procurement_officer', 'goods_receipt.create'),
  ('procurement_officer', 'goods_receipt.read'),
  ('finance_manager', 'supplier.read'),
  ('finance_manager', 'supplier.manage'),
  ('finance_manager', 'procurement.read'),
  ('finance_manager', 'purchase_order.read'),
  ('finance_manager', 'purchase_order.approve'),
  ('finance_manager', 'supplier_invoice.create'),
  ('finance_manager', 'supplier_invoice.read'),
  ('finance_manager', 'supplier_invoice.review'),
  ('finance_manager', 'supplier_invoice.approve'),
  ('finance_manager', 'supplier_payment.read'),
  ('finance_manager', 'supplier_payment.record'),
  ('finance_manager', 'supplier_payment.approve'),
  ('finance_manager', 'project_budget.read'),
  ('finance_manager', 'project_budget.manage'),
  ('finance_manager', 'finance.read'),
  ('finance_manager', 'finance.manage'),
  ('finance_manager', 'client_valuation.read'),
  ('finance_manager', 'client_invoice.create'),
  ('finance_manager', 'client_invoice.read'),
  ('finance_manager', 'client_invoice.issue'),
  ('finance_manager', 'client_payment.read'),
  ('finance_manager', 'client_payment.record'),
  ('finance_manager', 'variation.read'),
  ('finance_manager', 'variation.approve'),
  ('finance_manager', 'commercial_reports.read'),
  ('finance_officer', 'supplier.read'),
  ('finance_officer', 'supplier_invoice.create'),
  ('finance_officer', 'supplier_invoice.read'),
  ('finance_officer', 'supplier_invoice.review'),
  ('finance_officer', 'supplier_payment.read'),
  ('finance_officer', 'supplier_payment.record'),
  ('finance_officer', 'project_budget.read'),
  ('finance_officer', 'finance.read'),
  ('finance_officer', 'client_invoice.read'),
  ('finance_officer', 'client_payment.read'),
  ('finance_officer', 'client_payment.record'),
  ('finance_officer', 'commercial_reports.read')
) as x(code, permission_key) on x.code = r.code
on conflict do nothing;
